import { useMemo, useRef, useState } from "react";
import { Bot, ChevronDown, MessageCircle, Send, Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { useLanguage, type LanguageCode } from "@/context/LanguageContext";

type Message = { id: number; role: "user" | "bot"; text: string };

const RESPONSES: Record<LanguageCode, { welcome: string; placeholder: string; quick: string[]; answers: Record<string, string>; fallback: string }> = {
  en: { welcome: "Hi! I’m PramaanScan Assistant. Ask me about document verification, QR codes, signatures, AI analysis, or portals.", placeholder: "Ask about PramaanScan…", quick: ["How does verification work?", "What does VERIFIED mean?", "Is AI analysis authoritative?", "How do I use a QR code?"], answers: { verify: "PramaanScan hashes the exact uploaded file with SHA-256 and checks the registered Ed25519 signature. The cryptographic verdict is authoritative.", verified: "VERIFIED means the uploaded bytes match the registered SHA-256 fingerprint and the Ed25519 signature validates with an active signing key.", ai: "AI media analysis is advisory. It can flag possible manipulation patterns, but it never overrides the cryptographic verdict.", qr: "Scan the official QR code or open Verify Document, then upload the file or enter the verification code. Compare the result with the issuer and signed record.", key: "A compromised signing key can be revoked by an administrator. Future checks then report the affected signatures as REVOKED.", privacy: "Verification can work from the file fingerprint and registered metadata; the system does not need to retain your original file just to compare its hash." }, fallback: "I can help with verification, QR codes, signatures, AI analysis, revoked keys, privacy, and portal access. Try one of the quick questions." },
  hi: { welcome: "नमस्ते! मैं PramaanScan सहायक हूँ। दस्तावेज़ सत्यापन, QR, डिजिटल सिग्नेचर, AI विश्लेषण या पोर्टल के बारे में पूछें।", placeholder: "PramaanScan के बारे में पूछें…", quick: ["सत्यापन कैसे होता है?", "VERIFIED का मतलब?", "क्या AI analysis अंतिम है?", "QR कैसे इस्तेमाल करें?"], answers: { verify: "PramaanScan आपकी फ़ाइल का SHA-256 fingerprint बनाकर registered Ed25519 signature से मिलाता है। Cryptographic verdict अंतिम प्रमाण है।", verified: "VERIFIED का अर्थ है कि अपलोड की गई फ़ाइल का SHA-256 fingerprint registered record से मिलता है और Ed25519 signature active key से valid है।", ai: "AI media analysis केवल advisory है। यह संभावित manipulation बता सकता है, लेकिन cryptographic verdict को नहीं बदलता।", qr: "Official QR scan करें या Verify Document खोलें। फिर फ़ाइल upload करें या verification code डालें और issuer के record से परिणाम मिलाएँ।", key: "अगर signing key compromised हो जाए तो administrator उसे revoke कर सकता है। उसके बाद संबंधित checks REVOKED दिखेंगे।", privacy: "Verification के लिए file fingerprint और registered metadata पर्याप्त हैं; केवल hash compare करने के लिए original file को रखना जरूरी नहीं है।" }, fallback: "मैं verification, QR, signatures, AI analysis, revoked keys, privacy और portal access में मदद कर सकता हूँ। Quick question चुनें।" },
  or: { welcome: "ନମସ୍କାର! ମୁଁ PramaanScan ସହାୟକ। ଦଲିଲ ସତ୍ୟାପନ, QR, ସିଗ୍ନେଚର୍, AI ବିଶ୍ଳେଷଣ କିମ୍ବା ପୋର୍ଟାଲ ବିଷୟରେ ପଚାରନ୍ତୁ।", placeholder: "PramaanScan ବିଷୟରେ ପଚାରନ୍ତୁ…", quick: ["ସତ୍ୟାପନ କିପରି ହୁଏ?", "VERIFIED ର ଅର୍ଥ?", "AI analysis କି ଅନ୍ତିମ?", "QR କିପରି ବ୍ୟବହାର କରିବି?"], answers: { verify: "PramaanScan ଫାଇଲର SHA-256 fingerprint ତିଆରି କରି registered Ed25519 signature ସହିତ ଯାଞ୍ଚ କରେ। Cryptographic verdict ହିଁ ଅଧିକାରିକ ପ୍ରମାଣ।", verified: "VERIFIED ଅର୍ଥ ହେଉଛି ଅପଲୋଡ୍ ହୋଇଥିବା ଫାଇଲର fingerprint registered record ସହିତ ମେଳ ଖାଏ ଏବଂ Ed25519 signature valid ଅଟେ।", ai: "AI media analysis କେବଳ advisory। ଏହା manipulation ସମ୍ଭାବନା ଦେଖାଏ, କିନ୍ତୁ cryptographic verdict ବଦଳାଏ ନାହିଁ।", qr: "Official QR scan କରନ୍ତୁ କିମ୍ବା Verify Document ଖୋଲନ୍ତୁ, ପରେ file upload କିମ୍ବା verification code ଦିଅନ୍ତୁ।", key: "Signing key compromised ହେଲେ administrator ତାହା revoke କରିପାରନ୍ତି। ପରବର୍ତ୍ତୀ checks REVOKED ଦେଖାଇବ।", privacy: "Verification ପାଇଁ fingerprint ଓ registered metadata ପର୍ଯ୍ୟାପ୍ତ; କେବଳ hash compare ପାଇଁ original file ରଖିବା ଆବଶ୍ୟକ ନାହିଁ।" }, fallback: "ମୁଁ verification, QR, signature, AI analysis, revoked keys, privacy ଏବଂ portal access ବିଷୟରେ ସହାୟତା କରିପାରିବି।" },
  bn: { welcome: "নমস্কার! আমি PramaanScan সহায়ক। নথি যাচাই, QR, স্বাক্ষর, AI বিশ্লেষণ বা পোর্টাল নিয়ে জিজ্ঞাসা করুন।", placeholder: "PramaanScan সম্পর্কে জিজ্ঞাসা করুন…", quick: ["যাচাই কীভাবে হয়?", "VERIFIED মানে কী?", "AI analysis কি চূড়ান্ত?", "QR কীভাবে ব্যবহার করব?"], answers: { verify: "PramaanScan ফাইলের SHA-256 fingerprint তৈরি করে registered Ed25519 signature যাচাই করে। Cryptographic verdict-ই চূড়ান্ত প্রমাণ।", verified: "VERIFIED মানে আপলোড করা ফাইলের fingerprint registered record-এর সঙ্গে মেলে এবং Ed25519 signature valid।", ai: "AI media analysis পরামর্শমূলক। এটি সম্ভাব্য manipulation দেখাতে পারে, কিন্তু cryptographic verdict বদলায় না।", qr: "Official QR scan করুন অথবা Verify Document খুলুন, তারপর file upload বা verification code দিন।", key: "Signing key compromised হলে administrator সেটি revoke করতে পারেন; পরের checks REVOKED দেখাবে।", privacy: "Verification-এর জন্য fingerprint ও registered metadata যথেষ্ট; শুধু hash compare করার জন্য original file রাখা দরকার নেই।" }, fallback: "আমি verification, QR, signatures, AI analysis, revoked keys, privacy এবং portal access নিয়ে সাহায্য করতে পারি।" },
  te: { welcome: "నమస్కారం! నేను PramaanScan సహాయకుడిని. పత్ర ధృవీకరణ, QR, సంతకాలు, AI విశ్లేషణ లేదా పోర్టల్ గురించి అడగండి.", placeholder: "PramaanScan గురించి అడగండి…", quick: ["ధృవీకరణ ఎలా జరుగుతుంది?", "VERIFIED అంటే ఏమిటి?", "AI analysis తుది ఫలితమా?", "QR ఎలా ఉపయోగించాలి?"], answers: { verify: "PramaanScan ఫైల్ యొక్క SHA-256 fingerprint ను తయారు చేసి registered Ed25519 signature ను తనిఖీ చేస్తుంది. Cryptographic verdict అధికారిక ఆధారం.", verified: "VERIFIED అంటే upload చేసిన ఫైల్ fingerprint registered record తో సరిపోతుంది మరియు Ed25519 signature valid గా ఉంది.", ai: "AI media analysis advisory మాత్రమే. ఇది manipulation అవకాశాలను సూచించగలదు కానీ cryptographic verdict ను మార్చదు.", qr: "Official QR ను scan చేయండి లేదా Verify Document తెరవండి. తరువాత file upload చేయండి లేదా verification code నమోదు చేయండి.", key: "Signing key compromise అయితే administrator దాన్ని revoke చేయవచ్చు. తరువాత checks REVOKED చూపిస్తాయి.", privacy: "Verification కు fingerprint మరియు registered metadata సరిపోతాయి; hash compare కోసం original file నిల్వ చేయాల్సిన అవసరం లేదు." }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy మరియు portal access గురించి నేను సహాయం చేయగలను." },
  ta: { welcome: "வணக்கம்! நான் PramaanScan உதவியாளர். ஆவண சரிபார்ப்பு, QR, கையொப்பம், AI பகுப்பாய்வு அல்லது போர்டல் பற்றி கேளுங்கள்.", placeholder: "PramaanScan பற்றி கேளுங்கள்…", quick: ["சரிபார்ப்பு எப்படி நடக்கும்?", "VERIFIED என்றால் என்ன?", "AI analysis இறுதியானதா?", "QR எப்படி பயன்படுத்துவது?"], answers: { verify: "PramaanScan கோப்பின் SHA-256 fingerprint உருவாக்கி registered Ed25519 signature-ஐ சரிபார்க்கிறது. Cryptographic verdict தான் அதிகாரப்பூர்வ ஆதாரம்.", verified: "VERIFIED என்பது upload செய்த கோப்பின் fingerprint registered record-உடன் பொருந்தி Ed25519 signature valid ஆக இருப்பது.", ai: "AI media analysis ஆலோசனை மட்டுமே. இது manipulation சாத்தியத்தை காட்டலாம்; cryptographic verdict-ஐ மாற்றாது.", qr: "Official QR-ஐ scan செய்யவும் அல்லது Verify Document திறக்கவும்; பின்னர் file upload அல்லது verification code பயன்படுத்தவும்.", key: "Signing key பாதிக்கப்பட்டால் administrator அதை revoke செய்யலாம். அடுத்த checks REVOKED என காட்டும்.", privacy: "Verification-க்கு fingerprint மற்றும் registered metadata போதும்; hash compare செய்வதற்காக original file சேமிக்க வேண்டியதில்லை." }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy மற்றும் portal access குறித்து உதவ முடியும்." },
  mr: { welcome: "नमस्कार! मी PramaanScan सहाय्यक आहे. दस्तऐवज पडताळणी, QR, स्वाक्षरी, AI विश्लेषण किंवा पोर्टलबद्दल विचारा.", placeholder: "PramaanScan बद्दल विचारा…", quick: ["पडताळणी कशी होते?", "VERIFIED म्हणजे काय?", "AI analysis अंतिम आहे का?", "QR कसा वापरायचा?"], answers: { verify: "PramaanScan फाइलचा SHA-256 fingerprint तयार करून registered Ed25519 signature तपासते. Cryptographic verdict हा अधिकृत पुरावा आहे.", verified: "VERIFIED म्हणजे upload केलेल्या फाइलचा fingerprint registered record शी जुळतो आणि Ed25519 signature valid आहे.", ai: "AI media analysis फक्त advisory आहे. ते manipulation ची शक्यता दाखवू शकते, पण cryptographic verdict बदलत नाही.", qr: "Official QR scan करा किंवा Verify Document उघडा; नंतर file upload करा किंवा verification code द्या.", key: "Signing key compromised असल्यास administrator ती revoke करू शकतो. त्यानंतर checks REVOKED दाखवतील.", privacy: "Verification साठी fingerprint आणि registered metadata पुरेसे आहेत; फक्त hash compare करण्यासाठी original file ठेवणे आवश्यक नाही." }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy आणि portal access मध्ये मी मदत करू शकतो." },
  gu: { welcome: "નમસ્તે! હું PramaanScan સહાયક છું. દસ્તાવેજ ચકાસણી, QR, સહી, AI વિશ્લેષણ અથવા પોર્ટલ વિશે પૂછો.", placeholder: "PramaanScan વિશે પૂછો…", quick: ["ચકાસણી કેવી રીતે થાય?", "VERIFIED એટલે શું?", "AI analysis અંતિમ છે?", "QR કેવી રીતે વાપરવું?"], answers: { verify: "PramaanScan ફાઇલનું SHA-256 fingerprint બનાવી registered Ed25519 signature ચકાસે છે. Cryptographic verdict સત્તાવાર પુરાવો છે.", verified: "VERIFIED એટલે upload કરેલી ફાઇલનું fingerprint registered record સાથે મળે છે અને Ed25519 signature valid છે.", ai: "AI media analysis માત્ર advisory છે. તે manipulation ની શક્યતા બતાવી શકે છે, પરંતુ cryptographic verdict બદલી શકતું નથી.", qr: "Official QR scan કરો અથવા Verify Document ખોલો; પછી file upload કરો અથવા verification code દાખલ કરો.", key: "Signing key compromised થાય તો administrator તેને revoke કરી શકે છે. ત્યાર પછી checks REVOKED બતાવશે.", privacy: "Verification માટે fingerprint અને registered metadata પૂરતા છે; hash compare માટે original file રાખવાની જરૂર નથી." }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy અને portal access માટે હું મદદ કરી શકું છું." },
  kn: { welcome: "ನಮಸ್ಕಾರ! ನಾನು PramaanScan ಸಹಾಯಕ. ದಾಖಲೆ ಪರಿಶೀಲನೆ, QR, ಸಹಿ, AI ವಿಶ್ಲೇಷಣೆ ಅಥವಾ ಪೋರ್ಟಲ್ ಕುರಿತು ಕೇಳಿ.", placeholder: "PramaanScan ಕುರಿತು ಕೇಳಿ…", quick: ["ಪರಿಶೀಲನೆ ಹೇಗೆ ನಡೆಯುತ್ತದೆ?", "VERIFIED ಎಂದರೇನು?", "AI analysis ಅಂತಿಮವೇ?", "QR ಹೇಗೆ ಬಳಸುವುದು?"], answers: { verify: "PramaanScan ಫೈಲ್‌ನ SHA-256 fingerprint ರಚಿಸಿ registered Ed25519 signature ಪರಿಶೀಲಿಸುತ್ತದೆ. Cryptographic verdict ಅಧಿಕೃತ ಸಾಕ್ಷ್ಯ.", verified: "VERIFIED ಎಂದರೆ upload ಮಾಡಿದ ಫೈಲ್ fingerprint registered record ಗೆ ಹೊಂದಿದ್ದು Ed25519 signature valid ಆಗಿದೆ.", ai: "AI media analysis ಸಲಹೆ ಮಾತ್ರ. ಇದು manipulation ಸಾಧ್ಯತೆಯನ್ನು ಸೂಚಿಸಬಹುದು, ಆದರೆ cryptographic verdict ಬದಲಿಸುವುದಿಲ್ಲ.", qr: "Official QR scan ಮಾಡಿ ಅಥವಾ Verify Document ತೆರೆಯಿರಿ; ನಂತರ file upload ಅಥವಾ verification code ಬಳಸಿ.", key: "Signing key compromised ಆದರೆ administrator ಅದನ್ನು revoke ಮಾಡಬಹುದು. ನಂತರ checks REVOKED ತೋರಿಸುತ್ತವೆ.", privacy: "Verification ಗೆ fingerprint ಮತ್ತು registered metadata ಸಾಕು; hash compare ಗಾಗಿ original file ಉಳಿಸಬೇಕಾಗಿಲ್ಲ." }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy ಮತ್ತು portal access ಬಗ್ಗೆ ನಾನು ಸಹಾಯ ಮಾಡಬಹುದು." },
  ml: { welcome: "നമസ്കാരം! ഞാൻ PramaanScan സഹായി. രേഖ പരിശോധന, QR, ഒപ്പ്, AI വിശകലനം അല്ലെങ്കിൽ പോർട്ടൽ സംബന്ധിച്ച് ചോദിക്കൂ.", placeholder: "PramaanScan കുറിച്ച് ചോദിക്കൂ…", quick: ["പരിശോധന എങ്ങനെ നടക്കും?", "VERIFIED എന്നാൽ എന്ത്?", "AI analysis അന്തിമമാണോ?", "QR എങ്ങനെ ഉപയോഗിക്കാം?"], answers: { verify: "PramaanScan ഫയലിന്റെ SHA-256 fingerprint ഉണ്ടാക്കി registered Ed25519 signature പരിശോധിക്കുന്നു. Cryptographic verdict ആണ് ഔദ്യോഗിക തെളിവ്.", verified: "VERIFIED എന്നത് upload ചെയ്ത ഫയലിന്റെ fingerprint registered record-ുമായി പൊരുത്തപ്പെടുകയും Ed25519 signature valid ആകുകയും ചെയ്യുന്നതാണ്.", ai: "AI media analysis ഉപദേശപരമാണ്. manipulation സാധ്യത സൂചിപ്പിക്കാം, പക്ഷേ cryptographic verdict മാറ്റില്ല.", qr: "Official QR scan ചെയ്യുക അല്ലെങ്കിൽ Verify Document തുറക്കുക; തുടർന്ന് file upload അല്ലെങ്കിൽ verification code ഉപയോഗിക്കുക.", key: "Signing key compromised ആണെങ്കിൽ administrator അത് revoke ചെയ്യാം. പിന്നീട് checks REVOKED കാണിക്കും.", privacy: "Verification-ന് fingerprint, registered metadata എന്നിവ മതിയാകും; hash compare ചെയ്യാൻ original file സൂക്ഷിക്കേണ്ടതില്ല." }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy, portal access എന്നിവയിൽ സഹായിക്കാം." },
  pa: { welcome: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ PramaanScan ਸਹਾਇਕ ਹਾਂ। ਦਸਤਾਵੇਜ਼ ਪੁਸ਼ਟੀ, QR, ਦਸਤਖਤ, AI ਵਿਸ਼ਲੇਸ਼ਣ ਜਾਂ ਪੋਰਟਲ ਬਾਰੇ ਪੁੱਛੋ।", placeholder: "PramaanScan ਬਾਰੇ ਪੁੱਛੋ…", quick: ["ਪੁਸ਼ਟੀ ਕਿਵੇਂ ਹੁੰਦੀ ਹੈ?", "VERIFIED ਦਾ ਕੀ ਮਤਲਬ?", "ਕੀ AI analysis ਅੰਤਿਮ ਹੈ?", "QR ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ?"], answers: { verify: "PramaanScan ਫਾਈਲ ਦਾ SHA-256 fingerprint ਬਣਾਕੇ registered Ed25519 signature ਦੀ ਜਾਂਚ ਕਰਦਾ ਹੈ। Cryptographic verdict ਅਧਿਕਾਰਤ ਸਬੂਤ ਹੈ।", verified: "VERIFIED ਦਾ ਮਤਲਬ ਹੈ upload ਕੀਤੀ ਫਾਈਲ ਦਾ fingerprint registered record ਨਾਲ ਮਿਲਦਾ ਹੈ ਅਤੇ Ed25519 signature valid ਹੈ।", ai: "AI media analysis ਸਿਰਫ਼ advisory ਹੈ। ਇਹ manipulation ਦੀ ਸੰਭਾਵਨਾ ਦੱਸ ਸਕਦਾ ਹੈ ਪਰ cryptographic verdict ਨਹੀਂ ਬਦਲਦਾ।", qr: "Official QR scan ਕਰੋ ਜਾਂ Verify Document ਖੋਲ੍ਹੋ; ਫਿਰ file upload ਕਰੋ ਜਾਂ verification code ਦਿਓ।", key: "Signing key compromised ਹੋਵੇ ਤਾਂ administrator ਇਸਨੂੰ revoke ਕਰ ਸਕਦਾ ਹੈ। ਅਗਲੇ checks REVOKED ਦਿਖਾਉਣਗੇ।", privacy: "Verification ਲਈ fingerprint ਅਤੇ registered metadata ਕਾਫ਼ੀ ਹਨ; hash compare ਲਈ original file ਰੱਖਣ ਦੀ ਲੋੜ ਨਹੀਂ।" }, fallback: "ਮੈਂ verification, QR, signatures, AI analysis, revoked keys, privacy ਅਤੇ portal access ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ।" },
  as: { welcome: "নমস্কাৰ! মই PramaanScan সহায়ক। নথি পৰীক্ষা, QR, স্বাক্ষৰ, AI বিশ্লেষণ বা প’ৰ্টেলৰ বিষয়ে সোধক।", placeholder: "PramaanScanৰ বিষয়ে সোধক…", quick: ["পৰীক্ষা কেনেকৈ হয়?", "VERIFIED মানে কি?", "AI analysis চূড়ান্ত নেকি?", "QR কেনেকৈ ব্যৱহাৰ কৰিম?"], answers: { verify: "PramaanScan-এ ফাইলৰ SHA-256 fingerprint তৈয়াৰ কৰি registered Ed25519 signature পৰীক্ষা কৰে। Cryptographic verdict-ই চৰকাৰী প্ৰমাণ।", verified: "VERIFIED মানে upload কৰা ফাইলৰ fingerprint registered record-ৰ সৈতে মিলিছে আৰু Ed25519 signature valid।", ai: "AI media analysis কেৱল advisory। ই manipulation-ৰ সম্ভাৱনা দেখুৱাব পাৰে, কিন্তু cryptographic verdict সলনি নকৰে।", qr: "Official QR scan কৰক বা Verify Document খোলক; তাৰ পিছত file upload বা verification code ব্যৱহাৰ কৰক।", key: "Signing key compromised হলে administrator-এ তাক revoke কৰিব পাৰে। পিছৰ checks REVOKED দেখুৱাব।", privacy: "Verification-ৰ বাবে fingerprint আৰু registered metadata যথেষ্ট; hash compare কৰিবলৈ original file ৰাখিব নালাগে।" }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy আৰু portal access-ত সহায় কৰিব পাৰোঁ।" },
  ur: { welcome: "السلام علیکم! میں PramaanScan معاون ہوں۔ دستاویز کی تصدیق، QR، دستخط، AI تجزیہ یا پورٹل کے بارے میں پوچھیں۔", placeholder: "PramaanScan کے بارے میں پوچھیں…", quick: ["تصدیق کیسے ہوتی ہے؟", "VERIFIED کا مطلب؟", "کیا AI analysis حتمی ہے؟", "QR کیسے استعمال کریں؟"], answers: { verify: "PramaanScan فائل کا SHA-256 fingerprint بنا کر registered Ed25519 signature چیک کرتا ہے۔ Cryptographic verdict مستند ثبوت ہے۔", verified: "VERIFIED کا مطلب ہے کہ upload کی گئی فائل کا fingerprint registered record سے ملتا ہے اور Ed25519 signature valid ہے۔", ai: "AI media analysis صرف advisory ہے۔ یہ ممکنہ manipulation بتا سکتا ہے لیکن cryptographic verdict تبدیل نہیں کرتا۔", qr: "Official QR scan کریں یا Verify Document کھولیں، پھر file upload یا verification code استعمال کریں۔", key: "Signing key compromised ہو تو administrator اسے revoke کر سکتا ہے۔ بعد کی checks REVOKED دکھائیں گی۔", privacy: "Verification کے لیے fingerprint اور registered metadata کافی ہیں؛ صرف hash compare کے لیے original file رکھنا ضروری نہیں۔" }, fallback: "میں verification، QR، signatures، AI analysis، revoked keys، privacy اور portal access میں مدد کر سکتا ہوں۔" },
  sa: { welcome: "नमस्ते! अहं PramaanScan-सहायकः अस्मि। दस्तावेजसत्यापनं, QR, हस्ताक्षरं, AI-विश्लेषणं वा पोर्टलविषये पृच्छतु।", placeholder: "PramaanScan विषये पृच्छतु…", quick: ["सत्यापनं कथं भवति?", "VERIFIED इत्यस्य अर्थः?", "AI analysis अन्तिमं वा?", "QR कथं उपयोजयेत्?"], answers: { verify: "PramaanScan SHA-256 fingerprint निर्माय registered Ed25519 signature परीक्षते। Cryptographic verdict एव प्रमाणम्।", verified: "VERIFIED इत्यस्य अर्थः uploaded file fingerprint registered record सह मेलति तथा Ed25519 signature valid अस्ति।", ai: "AI media analysis केवलम् advisory अस्ति। तत् manipulation-संभावनां दर्शयितुं शक्नोति, परन्तु cryptographic verdict न परिवर्तयति।", qr: "Official QR scan करोतु अथवा Verify Document उद्घाटयतु, ततः file upload वा verification code उपयोजयतु।", key: "Signing key compromised चेत् administrator तं revoke कर्तुं शक्नोति। अनन्तरं checks REVOKED दर्शयिष्यन्ति।", privacy: "Verification हेतु fingerprint तथा registered metadata पर्याप्तम्; hash compare कृते original file स्थापयितुं न आवश्यकम्।" }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy तथा portal access विषये अहं सहाय्यं कर्तुं शक्नोमि।" },
  kok: { welcome: "नमस्कार! हांव PramaanScan सहाय्यक. दस्तावेज तपासणी, QR, सही, AI विश्लेषण वा पोर्टल विशीं विचारात.", placeholder: "PramaanScan विशीं विचारात…", quick: ["तपासणी कशी जाता?", "VERIFIED म्हणजें कितें?", "AI analysis शेवटचें आसा?", "QR कशें वापरचें?"], answers: { verify: "PramaanScan फायलचो SHA-256 fingerprint तयार करून registered Ed25519 signature तपासता. Cryptographic verdict अधिकृत पुरावो आसा.", verified: "VERIFIED म्हणजें upload केल्ल्या फायलचो fingerprint registered record कडेन मेळटा आनी Ed25519 signature valid आसा.", ai: "AI media analysis फकत advisory आसा. तो manipulation ची शक्यताय दाखोवू शकता, पण cryptographic verdict बदलना.", qr: "Official QR scan करात वा Verify Document उगडात; उपरांत file upload वा verification code वापरात.", key: "Signing key compromised जाल्यार administrator ती revoke करूंक शकता. फुडले checks REVOKED दाखयतले.", privacy: "Verification खातीर fingerprint आनी registered metadata पुरे; hash compare खातीर original file दवरपाची गरज ना." }, fallback: "Verification, QR, signatures, AI analysis, revoked keys, privacy आनी portal access विशीं हांव मदत करूंक शकता." },
  ne: { welcome: "नमस्ते! म PramaanScan सहायक हुँ। कागजात प्रमाणीकरण, QR, हस्ताक्षर, AI विश्लेषण वा पोर्टलबारे सोध्नुहोस्।", placeholder: "PramaanScan बारे सोध्नुहोस्…", quick: ["प्रमाणीकरण कसरी हुन्छ?", "VERIFIED को अर्थ?", "AI analysis अन्तिम हो?", "QR कसरी प्रयोग गर्ने?"], answers: { verify: "PramaanScan ले फाइलको SHA-256 fingerprint बनाएर registered Ed25519 signature जाँच गर्छ। Cryptographic verdict आधिकारिक प्रमाण हो।", verified: "VERIFIED भनेको upload गरिएको फाइलको fingerprint registered record सँग मिल्छ र Ed25519 signature valid छ।", ai: "AI media analysis advisory मात्र हो। यसले manipulation को सम्भावना देखाउन सक्छ तर cryptographic verdict बदल्दैन।", qr: "Official QR scan गर्नुहोस् वा Verify Document खोल्नुहोस्; त्यसपछि file upload वा verification code प्रयोग गर्नुहोस्।", key: "Signing key compromised भए administrator ले revoke गर्न सक्छ। त्यसपछि checks REVOKED देखाउनेछन्।", privacy: "Verification का लागि fingerprint र registered metadata पर्याप्त छन्; hash compare गर्न original file राख्न आवश्यक छैन।" }, fallback: "म verification, QR, signatures, AI analysis, revoked keys, privacy र portal access मा मद्दत गर्न सक्छु।" },
};

function intentFor(text: string) {
  const value = text.toLowerCase();
  if (/(verified|verify|verification|सत्याप|सत्यापन|प्रमाण|ଯାଞ୍ଚ|ସତ୍ୟାପ|ধৃ|যাচাই|ధృవీక|சரிபா|पडताळ|ચકાસ|ಪರಿಶೀಲ|പരിശോധ|ਪੁਸ਼ਟੀ|পৰীক্ষ|تصدیق|सत्यय)/u.test(value)) return value.includes("verified") || value.includes("verified") || /verified/.test(value) ? "verified" : "verify";
  if (/(ai|analysis|विश्लेषण|ବିଶ୍ଳେଷଣ|বিশ্লেষণ|విశ్లేషణ|பகுப்பாய்வு|विश्लेषण|વિશ્લેષણ|ವಿಶ್ಲೇಷಣೆ|വിശകലനം|ਵਿਸ਼ਲੇਸ਼ਣ|বিশ্লেষণ|تجزیہ)/u.test(value)) return "ai";
  if (/(qr|कोड|କୋଡ୍|কোড|కోడ్|குறியீடு|कोड|કોડ|ಕೋಡ್|കോഡ്|ਕੋਡ|কোড|رمز)/u.test(value)) return "qr";
  if (/(key|revoke|revoked|की|key|କୀ|চাবি|కీ|விசை|कुंजी|કી|ಕೀ|കീ|ਕੁੰਜੀ|চাবি|کلید|कुंजी)/u.test(value)) return "key";
  if (/(privacy|stored|store|save|फाइल|ଫାଇଲ|ফাইল|ఫైల్|கோப்பு|फाइल|ફાઇલ|ಫೈಲ್|ഫയൽ|ਫਾਈਲ|ফাইল|فائل)/u.test(value)) return "privacy";
  return "fallback";
}

export function ChatAssistant() {
  const { language, t } = useLanguage();
  const copy = RESPONSES[language] ?? RESPONSES.en;
  const [open, setOpen] = useState(false);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Message[]>([]);
  const idRef = useRef(1);
  const suggestions = useMemo(() => copy.quick, [copy]);

  const addMessage = (text: string) => {
    const clean = text.trim();
    if (!clean) return;
    const userMessage: Message = { id: idRef.current++, role: "user", text: clean };
    const intent = intentFor(clean);
    const reply = intent === "fallback" ? copy.fallback : copy.answers[intent];
    const botMessage: Message = { id: idRef.current++, role: "bot", text: reply };
    setMessages((current) => [...current, userMessage, botMessage]);
    setInput("");
  };

  return (
    <div data-ps-no-translate="true" className="fixed bottom-5 right-5 z-[60] sm:bottom-6 sm:right-6">
      {open && (
        <div className="mb-3 flex w-[min(92vw,390px)] flex-col overflow-hidden rounded-2xl border border-border bg-background shadow-elevated">
          <div className="flex items-center justify-between bg-primary px-4 py-3 text-primary-foreground">
            <div className="flex items-center gap-2"><div className="rounded-lg bg-primary-foreground/15 p-1.5"><Bot className="h-4 w-4" /></div><div><p className="text-sm font-semibold">{t("Chat Assistant")}</p><p className="text-[11px] opacity-80">{language.toUpperCase()} · PramaanScan</p></div></div>
            <Button variant="ghost" size="icon" onClick={() => setOpen(false)} className="text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground" aria-label="Close"><X className="h-4 w-4" /></Button>
          </div>
          <div className="max-h-[48vh] min-h-56 space-y-3 overflow-y-auto p-4 scrollbar-thin">
            {messages.length === 0 && <div className="rounded-xl border border-primary/10 bg-primary/5 p-3 text-sm leading-6 text-foreground"><div className="mb-2 flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4 text-primary" /> {t("Chat Assistant")}</div>{copy.welcome}</div>}
            {messages.map((message) => <div key={message.id} data-ps-no-translate={message.role === "user" ? "true" : undefined} className={cn("max-w-[88%] rounded-2xl px-3.5 py-2.5 text-sm leading-5", message.role === "user" ? "ml-auto bg-primary text-primary-foreground" : "mr-auto bg-secondary text-foreground")}>{message.text}</div>)}
            {messages.length === 0 && <div className="space-y-2">{suggestions.map((suggestion) => <button key={suggestion} onClick={() => addMessage(suggestion)} className="block w-full rounded-xl border border-border px-3 py-2 text-left text-xs font-medium hover:border-primary/40 hover:bg-primary/5">{suggestion}</button>)}</div>}
          </div>
          <form onSubmit={(event) => { event.preventDefault(); addMessage(input); }} className="flex gap-2 border-t border-border p-3">
            <input value={input} onChange={(event) => setInput(event.target.value)} placeholder={copy.placeholder} className="min-w-0 flex-1 rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring" aria-label={copy.placeholder} />
            <Button type="submit" size="icon" disabled={!input.trim()} aria-label={t("Send")}><Send className="h-4 w-4" /></Button>
          </form>
        </div>
      )}
      <Button onClick={() => setOpen((value) => !value)} size="lg" className="h-12 rounded-full px-4 shadow-elevated" aria-label={t("Chat Assistant")}>
        {open ? <ChevronDown className="h-5 w-5" /> : <MessageCircle className="h-5 w-5" />}
        <span className="hidden sm:inline">{t("Chat Assistant")}</span>
      </Button>
    </div>
  );
}
